/*
    @Date			              : 24.06.2020
    @Author                       : Stein Lundbeck
*/

using LundbeckConsulting.Components.Core;
using LundbeckConsulting.Components.Core.Components;
using LundbeckConsulting.Components.Extensions;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;

namespace Creator.Components.TagHelpers.Icon
{
    public interface IIconHelper
    {
        /// <summary>
        /// Gets the size record equal to size
        /// </summary>
        /// <param name="size">Icon size</param>
        /// <returns>Record equal to size</returns>
        IIconSizeRecord GetSize(IconSize size);

        /// <summary>
        /// Gets the tag name based on output format
        /// </summary>
        string GetFormatTagName(IconOutputFormat format);

        /// <summary>
        /// Adds attributes for an anchor tag
        /// </summary>
        /// <param name="tag">Tag to process</param>
        /// <returns>Tag with added anchor attributes</returns>
        TagBuilderCustom ProcessAnchorTag(TagBuilderCustom tag, string href, TagAnchorTarget target = TagAnchorTarget.None);

        /// <summary>
        /// Gets an icon of either type FontAwesome, Friconix or Captain Icon
        /// </summary>
        /// <param name="icon">Type of icon</param>
        /// <returns>The icon</returns>
        IIconRecord GetIcon(Enum icon);

        /// <summary>
        /// Gets a formated name of the icon
        /// </summary>
        /// <param name="icon">Type of icon</param>
        /// <returns>Formated icon name</returns>
        string GetCaptainIconName(CaptainIcon icon);

        /// <summary>
        /// Gets a tag pointing to a Font Awesome icon
        /// </summary>
        /// <param name="icon"></param>
        /// <returns></returns>
        TagBuilderCustom GetFontAwesomeTag(FontAwesomeIcon icon, IconSize size = IconSize.None);
    }

    /// <summary>
    /// Contains different functions for the IconTagHelper
    /// </summary>
    public sealed class IconHelper : IIconHelper
    {
        private readonly ICollection<IIconRecord> _iconArchive;
        private readonly ICollection<IIconSizeRecord> _sizeArchive;

        public IconHelper()
        {
            _iconArchive = new Collection<IIconRecord>();
            _sizeArchive = new Collection<IIconSizeRecord>()
            {
                new IconSizeRecord(IconSize.XXS, "fa-xs", "t", "0.4rem"),
                new IconSizeRecord(IconSize.XS, "fa-sm", "s", "0.8rem"),
                new IconSizeRecord(IconSize.SM, "fa-lg", "m", "1rem"),
                new IconSizeRecord(IconSize.MD, "fa-2x", "l", "1.4rem"),
                new IconSizeRecord(IconSize.Normal, "fa-xs", "s", "1.6rem"),
                new IconSizeRecord(IconSize.LG, "fa-4x", "h", "2rem"),
                new IconSizeRecord(IconSize.XL, "fa-5x", "4", "2.6rem"),
                new IconSizeRecord(IconSize.XXL, "fa-6x", "x", "3.1rem"),
                new IconSizeRecord(IconSize.XXXL, "fa-7x", "x", "4rem"),
                new IconSizeRecord(IconSize.X7, "fa-8x", "7", "4.9rem"),
                new IconSizeRecord(IconSize.X8, "fa-9x", "8", "5.4rem"),
                new IconSizeRecord(IconSize.X9, "fa-10x", "9", "6.2rem")
            };

            #region Icon records
            _iconArchive.AddRange(new IIconRecord[] {
                new IconRecord(FontAwesomeIcon.Box, "box"),
                new IconRecord(FontAwesomeIcon.BoxOpen, "box-open"),
                new IconRecord(FontAwesomeIcon.Boxes, "boxes"),
                new IconRecord(FontAwesomeIcon.Tools, "tools"),
                new IconRecord(FontAwesomeIcon.Save, "save", "far"),
                new IconRecord(FontAwesomeIcon.SaveFull, "save"),
                new IconRecord(FontAwesomeIcon.Close, "window-close", "far"),
                new IconRecord(FontAwesomeIcon.CloseFull, "save"),
                new IconRecord(FontAwesomeIcon.CloseCircle, "times-circle", "far"),
                new IconRecord(FontAwesomeIcon.CloseCircleFull, "save"),
                new IconRecord(FontAwesomeIcon.Camera, "camera"),
                new IconRecord(FontAwesomeIcon.BorderAll, "border-all"),
                new IconRecord(FontAwesomeIcon.SignIn, "sign-in-alt"),
                new IconRecord(FontAwesomeIcon.SignOut, "sign-out-alt"),
                new IconRecord(FontAwesomeIcon.Doc, "file-alt", "far"),
                new IconRecord(FontAwesomeIcon.DocCode, "file-code", "far"),
                new IconRecord(FontAwesomeIcon.DocImage, "file-image", "far"),
                new IconRecord(FontAwesomeIcon.DocPDF, "file-pdf", "far"),
                new IconRecord(FontAwesomeIcon.FileUpload, "file-upload"),
                new IconRecord(FontAwesomeIcon.FileDownload, "file-download"),
                new IconRecord(FontAwesomeIcon.FileExport, "file-export"),
                new IconRecord(FontAwesomeIcon.Lock, "lock"),
                new IconRecord(FontAwesomeIcon.LockOpen, "lock-open"),
                new IconRecord(FontAwesomeIcon.Edit, "edit", "far"),
                new IconRecord(FontAwesomeIcon.EditFull, "edit"),
                new IconRecord(FontAwesomeIcon.Copy, "copy", "far"),
                new IconRecord(FontAwesomeIcon.CopyFull, "copy"),
                new IconRecord(FontAwesomeIcon.Cogs, "cogs"),
                new IconRecord(FontAwesomeIcon.X, "times"),
                new IconRecord(FontAwesomeIcon.ArrowLeft, "arrow-left"),
                new IconRecord(FontAwesomeIcon.ArrowRight, "arrow-right"),
                new IconRecord(FontAwesomeIcon.ArrowUp, "arrow-up"),
                new IconRecord(FontAwesomeIcon.ArrowDown, "arrow-down"),
                new IconRecord(FontAwesomeIcon.AngleLeft, "angle-left"),
                new IconRecord(FontAwesomeIcon.AngleRight, "angle-right"),
                new IconRecord(FontAwesomeIcon.AngleUp, "angle-up"),
                new IconRecord(FontAwesomeIcon.AngleDown, "angle-down"),
                new IconRecord(FontAwesomeIcon.Calendar, "calendar-alt", "far"),
                new IconRecord(FontAwesomeIcon.CalendarFull, "calendar-alt"),
                new IconRecord(FontAwesomeIcon.Building, "building", "far"),
                new IconRecord(FontAwesomeIcon.BuildingFull, "building"),
                new IconRecord(FontAwesomeIcon.Envelope, "envelope", "far"),
                new IconRecord(FontAwesomeIcon.EnvelopeFull, "envelope"),
                new IconRecord(FontAwesomeIcon.EnvelopeOpen, "envelope-open", "far"),
                new IconRecord(FontAwesomeIcon.EnvelopeOpenFull, "envelope-open"),
                new IconRecord(FontAwesomeIcon.AddressCard, "address-card", "far"),
                new IconRecord(FontAwesomeIcon.AddressCardFull, "address-card"),
                new IconRecord(FontAwesomeIcon.Phone, "phone"),
                new IconRecord(FontAwesomeIcon.PhoneFull, "phone-square"),
                new IconRecord(FontAwesomeIcon.Mobile, "mobile-alt"),
                new IconRecord(FontAwesomeIcon.MobileFull, "mobile"),
                new IconRecord(FontAwesomeIcon.Messenger, "facebook-messenger", "fab"),
                new IconRecord(FontAwesomeIcon.LaptopCode, "laptop-code"),
                new IconRecord(FontAwesomeIcon.Comment, "comment", "far"),
                new IconRecord(FontAwesomeIcon.CommentFull, "comment"),
                new IconRecord(FontAwesomeIcon.Comments, "comments", "far"),
                new IconRecord(FontAwesomeIcon.CommentsFull, "comments"),
                new IconRecord(FontAwesomeIcon.Like, "thumbs-up", "far"),
                new IconRecord(FontAwesomeIcon.LikeFull, "thumbs-up"),
                new IconRecord(FontAwesomeIcon.List, "list"),
                new IconRecord(FontAwesomeIcon.ListAlt, "list-alt", "far"),
                new IconRecord(FontAwesomeIcon.ListAltFull, "list-alt"),
                new IconRecord(FontAwesomeIcon.Home, "home"),
                new IconRecord(FontAwesomeIcon.HomeDamage, "house-damage"),
                new IconRecord(FontAwesomeIcon.Ghost, "ghost"),
                new IconRecord(FontAwesomeIcon.Bars, "bars"),
                new IconRecord(FontAwesomeIcon.GitHub, "github", "fab"),
                new IconRecord(FontAwesomeIcon.Globe, "globe"),
                new IconRecord(FontAwesomeIcon.GlobeEurope, "globe-europe"),
                new IconRecord(FontAwesomeIcon.AddressBook, "address-book", "far"),
                new IconRecord(FontAwesomeIcon.AddressBookFull, "address-book"),
                new IconRecord(FontAwesomeIcon.Folder, "folder", "far"),
                new IconRecord(FontAwesomeIcon.FolderFull, "folder"),
                new IconRecord(FontAwesomeIcon.FolderMinusFull, "folder-minus"),
                new IconRecord(FontAwesomeIcon.FolderPlusFull, "folder-plus"),
                new IconRecord(FontAwesomeIcon.FolderOpen, "folder-open", "far"),
                new IconRecord(FontAwesomeIcon.FileImage, "file-image", "far"),
                new IconRecord(FontAwesomeIcon.FileImageFull, "file-image"),
                new IconRecord(FontAwesomeIcon.FileAlt, "file-alt", "far"),
                new IconRecord(FontAwesomeIcon.FolderOpenFull, "folder-open"),
                new IconRecord(FontAwesomeIcon.UserCircle, "user-circle", "far"),
                new IconRecord(FontAwesomeIcon.UserCircleFull, "user-circle"),
                new IconRecord(FontAwesomeIcon.UserNinja, "user-ninja"),
                new IconRecord(FontAwesomeIcon.UserSpy, "user-secret"),
                new IconRecord(FontAwesomeIcon.UserTie, "user-tie"),
                new IconRecord(FontAwesomeIcon.User, "user", "far"),
                new IconRecord(FontAwesomeIcon.UserFull, "user"),
                new IconRecord(FontAwesomeIcon.Code, "code"),
                new IconRecord(FontAwesomeIcon.Diagram, "project-diagram"),
                new IconRecord(FontAwesomeIcon.Add, "plus-square", "far"),
                new IconRecord(FontAwesomeIcon.AddFull, "plus-square"),
                new IconRecord(FontAwesomeIcon.AddCircle, "plus-circle", "far"),
                new IconRecord(FontAwesomeIcon.AddCircleFull, "plus-circle"),
                new IconRecord(FontAwesomeIcon.ShoppingBasket, "shopping-basket"),
                new IconRecord(FontAwesomeIcon.ShoppingCart, "shopping-cart"),
                new IconRecord(FontAwesomeIcon.ShoppingCartPlus, "cart-plus"),
                new IconRecord(FontAwesomeIcon.ShoppingBag, "shopping-bag"),
                new IconRecord(FontAwesomeIcon.Handshake, "handshake"),
                new IconRecord(FontAwesomeIcon.HandshakeFull, "handshake", "far"),
                new IconRecord(FontAwesomeIcon.ThumbsUp, "thumbs-up", "far"),
                new IconRecord(FontAwesomeIcon.ThumbsUpFull, "thumbs-up"),
                new IconRecord(FontAwesomeIcon.ThumbsDown, "thumbs-down", "far"),
                new IconRecord(FontAwesomeIcon.ThumbsDownFull, "thumbs-down"),
                new IconRecord(FontAwesomeIcon.MoneyCheckout, "money-checkout-alt"),
                new IconRecord(FontAwesomeIcon.Truck, "truck"),
                new IconRecord(FontAwesomeIcon.Tasks, "tasks"),
                new IconRecord(FontAwesomeIcon.Visa, "cc-visa", "fab"),
                new IconRecord(FontAwesomeIcon.Stripe, "cc-stripe", "fab"),
                new IconRecord(FontAwesomeIcon.PayPal, "cc-paypal", "fab"),
                new IconRecord(FontAwesomeIcon.PayPalIcon, "paypal", "fab"),
                new IconRecord(FontAwesomeIcon.Mastercard, "cc-mastercard", "fab"),
                new IconRecord(FontAwesomeIcon.ApplePay, "cc-apple-pay", "fab"),
                new IconRecord(FontAwesomeIcon.ApplePayIcon, "apple-pay", "fab"),
                new IconRecord(FontAwesomeIcon.AmericanExpress, "cc-amex", "fab"),
                new IconRecord(FontAwesomeIcon.AmazonPay, "cc-amazon-pay", "fab"),
                new IconRecord(FontAwesomeIcon.AmazonPayIcon, "amazon-pay", "fab"),
                new IconRecord(FontAwesomeIcon.GoogleWallet, "google-wallet", "fab"),
                new IconRecord(FontAwesomeIcon.Upload, "upload"),
                new IconRecord(FontAwesomeIcon.UploadCloud, "cloud-upload-alt"),
                new IconRecord(FontAwesomeIcon.DownloadCloud, "cloud-download-alt"),
                new IconRecord(FontAwesomeIcon.Bullhorn, "bullhorn"),
                new IconRecord(FontAwesomeIcon.Smile, "smile", "far"),
                new IconRecord(FontAwesomeIcon.SmileFull, "smile"),
                new IconRecord(FontAwesomeIcon.SmileWink, "smile-wink", "far"),
                new IconRecord(FontAwesomeIcon.SmileWinkFull, "smile-wink"),
                new IconRecord(FontAwesomeIcon.SmileLaugh, "grin", "far"),
                new IconRecord(FontAwesomeIcon.SmileLaughFull, "grin"),
                new IconRecord(FontAwesomeIcon.UserPlusFull, "user-plus"),
                new IconRecord(FontAwesomeIcon.Check, "check"),
                new IconRecord(FontAwesomeIcon.CheckSquare, "check-square"),
                new IconRecord(FontAwesomeIcon.CheckSquareFull, "check-square"),
                new IconRecord(FontAwesomeIcon.CheckCircle, "check-circle", "far"),
                new IconRecord(FontAwesomeIcon.CheckCircleFull, "check-circle"),
                new IconRecord(FontAwesomeIcon.UserShield, "user-shield"),
                new IconRecord(FontAwesomeIcon.Search, "search"),
                new IconRecord(FontAwesomeIcon.SearchPlus, "search-plus"),
                new IconRecord(FontAwesomeIcon.SearchMinus, "search-minus"),
                new IconRecord(FontAwesomeIcon.SearchDollar, "search-dollar"),
                new IconRecord(FontAwesomeIcon.SearchLocation, "search-location"),
                new IconRecord(FontAwesomeIcon.ShieldVirus, "shield-virus"),
                new IconRecord(FontAwesomeIcon.ShieldAlt, "shield-alt"),
                new IconRecord(FontAwesomeIcon.UserLock, "user-lock"),
                new IconRecord(FontAwesomeIcon.Thumbstick, "thumbstick"),
                new IconRecord(FontAwesomeIcon.FacebookLogo, "facebook-f", "fab"),
                new IconRecord(FontAwesomeIcon.FacebookLogoCircle, "facebook", "fab"),
                new IconRecord(FontAwesomeIcon.FacebookLogoSquare, "facebook-square", "fab"),
                new IconRecord(FontAwesomeIcon.LinkedInLogo, "linkedin-in", "fab"),
                new IconRecord(FontAwesomeIcon.LinkedInLogoSquare, "linkedin", "fab"),
                new IconRecord(FontAwesomeIcon.DeleteTrash, "trash-alt", "far"),
                new IconRecord(FontAwesomeIcon.DeleteTrashBold, "trash-alt"),
                new IconRecord(FontAwesomeIcon.DeleteTrashFull, "trash"),
                new IconRecord(FontAwesomeIcon.DeleteMinusCircleFull, "minus-circle"),
                new IconRecord(FontAwesomeIcon.DeleteMinus, "minus"),
                new IconRecord(FontAwesomeIcon.DeleteMinusSquare, "minus-square", "far"),
                new IconRecord(FontAwesomeIcon.DeleteMinusSquareFull, "minus-square"),
                new IconRecord(FontAwesomeIcon.DeleteUser, "user-times"),
                new IconRecord(FontAwesomeIcon.DeleteUserMinus, "user-minus"),
                new IconRecord(FontAwesomeIcon.Eye, "eye", "far"),
                new IconRecord(FontAwesomeIcon.EyeBold, "eye", "fas"),
                new IconRecord(FontAwesomeIcon.GoogleIcon, "google", "fab"),
                new IconRecord(FontAwesomeIcon.GooglePlay, "google-play", "fab"),
                new IconRecord(FontAwesomeIcon.GoogleDrive, "google-drive", "fab"),
                new IconRecord(FontAwesomeIcon.Database, "database"),
                new IconRecord(FontAwesomeIcon.Pager, "pager"),
                new IconRecord(FontAwesomeIcon.Tag, "tag"),
                new IconRecord(FontAwesomeIcon.Tags, "tags"),
                new IconRecord(FontAwesomeIcon.Teeth, "teeth"),
                new IconRecord(FontAwesomeIcon.InstagramIcon, "instagram", "fab"),
                new IconRecord(FontAwesomeIcon.InstagramSquare, "instagram-square", "fab"),
                new IconRecord(FontAwesomeIcon.Percentage, "percentage"),
                new IconRecord(FontAwesomeIcon.Hashtag, "hashtag"),
                new IconRecord(FontAwesomeIcon.Users, "users"),
                new IconRecord(FontAwesomeIcon.UserFriends, "user-friends"),
                new IconRecord(FontAwesomeIcon.Info, "info"),
                new IconRecord(FontAwesomeIcon.InfoCircle, "info-circle"),
                new IconRecord(FontAwesomeIcon.Image, "image", "far"),
                new IconRecord(FontAwesomeIcon.ImageFull, "image"),
                new IconRecord(FontAwesomeIcon.Images, "images", "far"),
                new IconRecord(FontAwesomeIcon.ImagesFull, "images"),
                new IconRecord(FontAwesomeIcon.Swatchbook, "swatchbook"),
                new IconRecord(FontAwesomeIcon.Key, "key"),
                new IconRecord(FontAwesomeIcon.Times, "times"),
                new IconRecord(FontAwesomeIcon.PhotoVideo, "photo-video"),
                new IconRecord(FontAwesomeIcon.PaintBrush, "paint-brush"),
                new IconRecord(FontAwesomeIcon.PaintBrushWide, "brush"),
                new IconRecord(FontAwesomeIcon.PaintRoller, "paint-roller"),
                new IconRecord(FontAwesomeIcon.Palette, "palette"),
                new IconRecord(FontAwesomeIcon.IdBadge, "id-badge", "far"),
                new IconRecord(FontAwesomeIcon.IdBadgeFull, "id-badge"),
                new IconRecord(FontAwesomeIcon.IdCard, "id-card", "far"),
                new IconRecord(FontAwesomeIcon.IdCardFull, "id-card")
            });

            _iconArchive.AddRange(new IIconRecord[] {
                new IconRecord(FriconixIcon.Facebook, "facebook"),
                new IconRecord(FriconixIcon.GoogleLogo, "google-logo"),
                new IconRecord(FriconixIcon.AmazonLogo, "amazon"),
                new IconRecord(FriconixIcon.Shopify, "shopify"),
                new IconRecord(FriconixIcon.ShoppingCart, "shopping-cart"),
                new IconRecord(FriconixIcon.ShoppingCartSolid, "shopping-cart-solid"),
                new IconRecord(FriconixIcon.ShoppingCartWide, "shopping-cart-wide"),
                new IconRecord(FriconixIcon.ShoppingCartWide, "shopping-cart-wide"),
                new IconRecord(FriconixIcon.UserThin, "user-thin"),
                new IconRecord(FriconixIcon.UserCircle, "user-circle"),
                new IconRecord(FriconixIcon.UserSolid, "user-solid"),
                new IconRecord(FriconixIcon.User, "user"),
                new IconRecord(FriconixIcon.UserCircleSolid, "user-circle-solid"),
                new IconRecord(FriconixIcon.UserCircleThin, "user-circle-thin"),
                new IconRecord(FriconixIcon.UserLockSolid, "user-lock-solid"),
                new IconRecord(FriconixIcon.UserLockWide, "user-lock-wide"),
                new IconRecord(FriconixIcon.UserLock, "user-lock"),
                new IconRecord(FriconixIcon.UserUnlockSolid, "user-unlock-solid"),
                new IconRecord(FriconixIcon.UserLockThin, "user-lock-thin"),
                new IconRecord(FriconixIcon.UserUnlock, "user-unlock"),
                new IconRecord(FriconixIcon.UserCircleWide, "user-circle-wide"),
                new IconRecord(FriconixIcon.JavaScriptSquare, "js"),
                new IconRecord(FriconixIcon.PlusSolid, "plus-solid"),
                new IconRecord(FriconixIcon.WarningSolid, "warning-solid"),
                new IconRecord(FriconixIcon.Update, "update"),
                new IconRecord(FriconixIcon.TeamSolid, "team-solid"),
                new IconRecord(FriconixIcon.Check, "check"),
                new IconRecord(FriconixIcon.NetworkSolid, "network-solid")
            });

            _iconArchive.AddRange(new IIconRecord[] {
                new IconRecord(CaptainIcon.Home, "ci-home", "e600"),
                new IconRecord(CaptainIcon.HomeAlt, "ci-home-alt", "e6c1"),
                new IconRecord(CaptainIcon.Pin, "ci-pin", "e601"),
                new IconRecord(CaptainIcon.Comment, "ci-comment", "e602"),
                new IconRecord(CaptainIcon.CommentDots, "ci-comment-dots", "e603"),
                new IconRecord(CaptainIcon.Comments, "ci-comments", "e68c"),
                new IconRecord(CaptainIcon.Gear, "ci-gear", "e605"),
                new IconRecord(CaptainIcon.Gears, "ci-gears", "e606"),
                new IconRecord(CaptainIcon.Heart, "ci-heart", "e607"),
                new IconRecord(CaptainIcon.Lock, "ci-lock", "e608"),
                new IconRecord(CaptainIcon.LockOpened, "ci-lock-opened", "e609"),
                new IconRecord(CaptainIcon.Load, "ci-load", "e60a"),
                new IconRecord(CaptainIcon.Refresh, "ci-refresh", "e60b"),
                new IconRecord(CaptainIcon.Tachometer, "ci-tachometer", "e60d"),
                new IconRecord(CaptainIcon.Compass, "ci-compass", "e60e"),
                new IconRecord(CaptainIcon.Timer, "ci-timer", "e60f"),
                new IconRecord(CaptainIcon.Download, "ci-download", "e610"),
                new IconRecord(CaptainIcon.Upload, "ci-upload", "e611"),
                new IconRecord(CaptainIcon.Envelope, "ci-envelope", "e612"),
                new IconRecord(CaptainIcon.EnvelopeOpened, "ci-envelope-opened", "e764"),
                new IconRecord(CaptainIcon.EnvelopeIn, "ci-envelope-in", "e68a"),
                new IconRecord(CaptainIcon.EnvelopeOut, "ci-envelope-out", "e68b"),
                new IconRecord(CaptainIcon.Tag, "ci-tag", "e613"),
                new IconRecord(CaptainIcon.TagAlt, "ci-tag-alt", "e6e5"),
                new IconRecord(CaptainIcon.Eye, "ci-eye", "e614"),
                new IconRecord(CaptainIcon.Star, "ci-star", "e615"),
                new IconRecord(CaptainIcon.Mobile, "ci-mobile", "e616"),
                new IconRecord(CaptainIcon.Monitor, "ci-monitor", "e617"),
                new IconRecord(CaptainIcon.MusicPlayer, "ci-music-player", "e618"),
                new IconRecord(CaptainIcon.Camera, "ci-camera", "e619"),
                new IconRecord(CaptainIcon.Suitcase, "ci-suitcase", "e61a"),
                new IconRecord(CaptainIcon.Shelf, "ci-shelf", "e61b"),
                new IconRecord(CaptainIcon.Umbrela, "ci-umbrela", "e61c"),
                new IconRecord(CaptainIcon.Trash, "ci-trash", "e61d"),
                new IconRecord(CaptainIcon.ShoppingCart, "ci-shopping-cart", "e61f"),
                new IconRecord(CaptainIcon.ShoppingCartFull, "ci-shopping-cart-full", "e61e"),
                new IconRecord(CaptainIcon.Calendar, "ci-calendar", "e620"),
                new IconRecord(CaptainIcon.Gift, "ci-gift", "e621"),
                new IconRecord(CaptainIcon.TestTube, "ci-test-tube", "e622"),
                new IconRecord(CaptainIcon.PuzzlePiece, "ci-puzzle-piece", "e623"),
                new IconRecord(CaptainIcon.Sun, "ci-sun", "e624"),
                new IconRecord(CaptainIcon.SunAlt, "ci-sun-alt", "e6a1"),
                new IconRecord(CaptainIcon.Map, "ci-map", "e625"),
                new IconRecord(CaptainIcon.PaintBrush, "ci-paint-brush", "e626"),
                new IconRecord(CaptainIcon.Lightbulb, "ci-lightbulb", "e627"),
                new IconRecord(CaptainIcon.Phone, "ci-phone", "e628"),
                new IconRecord(CaptainIcon.BandAid, "ci-band-aid", "e629"),
                new IconRecord(CaptainIcon.ListUl, "ci-list-ul", "e62a"),
                new IconRecord(CaptainIcon.ListOl, "ci-list-ol", "e62b"),
                new IconRecord(CaptainIcon.Question, "ci-question", "e62c"),
                new IconRecord(CaptainIcon.File, "ci-file", "e62d"),
                new IconRecord(CaptainIcon.FileAlt, "ci-file-alt", "e62e"),
                new IconRecord(CaptainIcon.FileEdit, "ci-file-edit", "e652"),
                new IconRecord(CaptainIcon.FileFilled, "ci-file-filled", "e709"),
                new IconRecord(CaptainIcon.User, "ci-user", "e62f"),
                new IconRecord(CaptainIcon.UserAlt, "ci-user-alt", "e630"),
                new IconRecord(CaptainIcon.Users, "ci-users", "e631"),
                new IconRecord(CaptainIcon.UsersAlt, "ci-users-alt", "e632"),
                new IconRecord(CaptainIcon.Mouse, "ci-mouse", "e633"),
                new IconRecord(CaptainIcon.MousePointer, "ci-mouse-pointer", "e705"),
                new IconRecord(CaptainIcon.Keyboard, "ci-keyboard", "e634"),
                new IconRecord(CaptainIcon.KeyboardKey, "ci-keyboard-key", "e706"),
                new IconRecord(CaptainIcon.Pencil, "ci-pencil", "e635"),
                new IconRecord(CaptainIcon.Check, "ci-check", "e636"),
                new IconRecord(CaptainIcon.CheckSquared, "ci-check-squared", "e637"),
                new IconRecord(CaptainIcon.Times, "ci-times", "e638"),
                new IconRecord(CaptainIcon.TimesSquared, "ci-times-squared", "e639"),
                new IconRecord(CaptainIcon.Plus, "ci-plus", "e63a"),
                new IconRecord(CaptainIcon.Leaf, "ci-leaf", "e63c"),
                new IconRecord(CaptainIcon.LeafAlt, "ci-leaf-alt", "e753"),
                new IconRecord(CaptainIcon.LeafLeaf, "ci-leaf-leaf", "e707"),
                new IconRecord(CaptainIcon.Laptop, "ci-laptop", "e63d"),
                new IconRecord(CaptainIcon.Coffee, "ci-coffee", "e63e"),
                new IconRecord(CaptainIcon.CoffeeLong, "ci-coffee-long", "e6d7"),
                new IconRecord(CaptainIcon.Bolt, "ci-bolt", "e63f"),
                new IconRecord(CaptainIcon.Skull, "ci-skull", "e641"),
                new IconRecord(CaptainIcon.DiscCompact, "ci-disc-compact", "e642"),
                new IconRecord(CaptainIcon.Speaker, "ci-speaker", "e644"),
                new IconRecord(CaptainIcon.Microwave, "ci-microwave", "e645"),
                new IconRecord(CaptainIcon.Pen, "ci-pen", "e646"),
                new IconRecord(CaptainIcon.PenFountain, "ci-pen-fountain", "e6d8"),
                new IconRecord(CaptainIcon.PenNib, "ci-pen-nib", "e703"),
                new IconRecord(CaptainIcon.BatBaseball, "ci-bat-baseball", "e647"),
                new IconRecord(CaptainIcon.Phonograph, "ci-phonograph", "e648"),
                new IconRecord(CaptainIcon.PlugUsb, "ci-plug-usb", "e649"),
                new IconRecord(CaptainIcon.LampDesk, "ci-lamp-desk", "e64a"),
                new IconRecord(CaptainIcon.Gamepad, "ci-gamepad", "e64b"),
                new IconRecord(CaptainIcon.GamepadAlt, "ci-gamepad-alt", "e64c"),
                new IconRecord(CaptainIcon.Portrait, "ci-portrait", "e64d"),
                new IconRecord(CaptainIcon.Books, "ci-books", "e64e"),
                new IconRecord(CaptainIcon.Bag, "ci-bag", "e64f"),
                new IconRecord(CaptainIcon.Glasses, "ci-glasses", "e650"),
                new IconRecord(CaptainIcon.Box, "ci-box", "e651"),
                new IconRecord(CaptainIcon.BoxOpened, "ci-box-opened", "e685"),
                new IconRecord(CaptainIcon.Music, "ci-music", "e653"),
                new IconRecord(CaptainIcon.MusicNote, "ci-music-note", "e654"),
                new IconRecord(CaptainIcon.SearchPlus, "ci-search-plus", "e656"),
                new IconRecord(CaptainIcon.SearchMinus, "ci-search-minus", "e657"),
                new IconRecord(CaptainIcon.Utensils, "ci-utensils", "e658"),
                new IconRecord(CaptainIcon.Print, "ci-print", "e659"),
                new IconRecord(CaptainIcon.Facebook, "ci-facebook", "e65a"),
                new IconRecord(CaptainIcon.FacebookSquared, "ci-facebook-squared", "e65b"),
                new IconRecord(CaptainIcon.FacebookCircled, "ci-facebook-circled", "e65c"),
                new IconRecord(CaptainIcon.Twitter, "ci-twitter", "e65d"),
                new IconRecord(CaptainIcon.TwitterSquared, "ci-twitter-squared", "e65e"),
                new IconRecord(CaptainIcon.TwitterCircled, "ci-twitter-circled", "e65f"),
                new IconRecord(CaptainIcon.GooglePlus, "ci-google-plus", "e666"),
                new IconRecord(CaptainIcon.GooglePlusSquared, "ci-google-plus-squared", "e667"),
                new IconRecord(CaptainIcon.GooglePlusCircled, "ci-google-plus-circled", "e668"),
                new IconRecord(CaptainIcon.Rss, "ci-rss", "e669"),
                new IconRecord(CaptainIcon.RssSquared, "ci-rss-squared", "e66a"),
                new IconRecord(CaptainIcon.RssCircled, "ci-rss-circled", "e66b"),
                new IconRecord(CaptainIcon.Linkedin, "ci-linkedin", "e66c"),
                new IconRecord(CaptainIcon.LinkedinSquared, "ci-linkedin-squared", "e66d"),
                new IconRecord(CaptainIcon.LinkedinCircled, "ci-linkedin-circled", "e66e"),
                new IconRecord(CaptainIcon.Youtube, "ci-youtube", "e66f"),
                new IconRecord(CaptainIcon.Vevo, "ci-vevo", "e670"),
                new IconRecord(CaptainIcon.VevoSquared, "ci-vevo-squared", "e671"),
                new IconRecord(CaptainIcon.VevoCircled, "ci-vevo-circled", "e672"),
                new IconRecord(CaptainIcon.Whatsapp, "ci-whatsapp", "e678"),
                new IconRecord(CaptainIcon.WhatsappSquared, "ci-whatsapp-squared", "e679"),
                new IconRecord(CaptainIcon.WhatsappCircled, "ci-whatsapp-circled", "e67a"),
                new IconRecord(CaptainIcon.At, "ci-at", "e67e"),
                new IconRecord(CaptainIcon.Domino, "ci-domino", "e67f"),
                new IconRecord(CaptainIcon.Git, "ci-git", "e680"),
                new IconRecord(CaptainIcon.Website, "ci-website", "e681"),
                new IconRecord(CaptainIcon.Css, "ci-css", "e682"),
                new IconRecord(CaptainIcon.Fire, "ci-fire", "e683"),
                new IconRecord(CaptainIcon.Mustache, "ci-mustache", "e684"),
                new IconRecord(CaptainIcon.FolderOpened, "ci-folder-opened", "e686"),
                new IconRecord(CaptainIcon.Sitemap, "ci-sitemap", "e687"),
                new IconRecord(CaptainIcon.Usb, "ci-usb", "e688"),
                new IconRecord(CaptainIcon.ButtonClothing, "ci-button-clothing", "e689"),
                new IconRecord(CaptainIcon.Thumbtack, "ci-thumbtack", "e68e"),
                new IconRecord(CaptainIcon.ThumbtackAlt, "ci-thumbtack-alt", "e70a"),
                new IconRecord(CaptainIcon.AddressCard, "ci-address-card", "e68f"),
                new IconRecord(CaptainIcon.AddressCardAlt, "ci-address-card-alt", "e6a2"),
                new IconRecord(CaptainIcon.Cat, "ci-cat", "e690"),
                new IconRecord(CaptainIcon.Ghost, "ci-ghost", "e691"),
                new IconRecord(CaptainIcon.Chicken, "ci-chicken", "e692"),
                new IconRecord(CaptainIcon.Balloon, "ci-balloon", "e693"),
                new IconRecord(CaptainIcon.BalloonAlt, "ci-balloon-alt", "e643"),
                new IconRecord(CaptainIcon.BalloonFace, "ci-balloon-face", "e694"),
                new IconRecord(CaptainIcon.Rocket, "ci-rocket", "e696"),
                new IconRecord(CaptainIcon.Broccoli, "ci-broccoli", "e697"),
                new IconRecord(CaptainIcon.Onion, "ci-onion", "e698"),
                new IconRecord(CaptainIcon.Banana, "ci-banana", "e69a"),
                new IconRecord(CaptainIcon.BananaPeel, "ci-banana-peel", "e699"),
                new IconRecord(CaptainIcon.Croissant, "ci-croissant", "e69b"),
                new IconRecord(CaptainIcon.Elephant, "ci-elephant", "e69c"),
                new IconRecord(CaptainIcon.Octopus, "ci-octopus", "e69d"),
                new IconRecord(CaptainIcon.Bowling, "ci-bowling", "e69e"),
                new IconRecord(CaptainIcon.Orange, "ci-orange", "e69f"),
                new IconRecord(CaptainIcon.Watermelon, "ci-watermelon", "e6a0"),
                new IconRecord(CaptainIcon.Tape, "ci-tape", "e6a3"),
                new IconRecord(CaptainIcon.Page, "ci-page", "e6a4"),
                new IconRecord(CaptainIcon.Ruler, "ci-ruler", "e6a6"),
                new IconRecord(CaptainIcon.Lemon, "ci-lemon", "e6a7"),
                new IconRecord(CaptainIcon.Bicycle, "ci-bicycle", "e6a8"),
                new IconRecord(CaptainIcon.BallBaseball, "ci-ball-baseball", "e6a9"),
                new IconRecord(CaptainIcon.BallSoccer, "ci-ball-soccer", "e6aa"),
                new IconRecord(CaptainIcon.BallBasket, "ci-ball-basket", "e6ab"),
                new IconRecord(CaptainIcon.BallFootbal, "ci-ball-footbal", "e6ac"),
                new IconRecord(CaptainIcon.BallEight, "ci-ball-eight", "e6c8"),
                new IconRecord(CaptainIcon.Foot, "ci-foot", "e6ad"),
                new IconRecord(CaptainIcon.Mashroom, "ci-mashroom", "e6ae"),
                new IconRecord(CaptainIcon.Ship, "ci-ship", "e6af"),
                new IconRecord(CaptainIcon.Submarine, "ci-submarine", "e6b0"),
                new IconRecord(CaptainIcon.Log, "ci-log", "e6b1"),
                new IconRecord(CaptainIcon.Broom, "ci-broom", "e6b2"),
                new IconRecord(CaptainIcon.Bone, "ci-bone", "e6b3"),
                new IconRecord(CaptainIcon.Paw, "ci-paw", "e6b4"),
                new IconRecord(CaptainIcon.Hanger, "ci-hanger", "e6b5"),
                new IconRecord(CaptainIcon.Key, "ci-key", "e6b6"),
                new IconRecord(CaptainIcon.KeyAlt, "ci-key-alt", "e73f"),
                new IconRecord(CaptainIcon.Spaceship, "ci-spaceship", "e6b7"),
                new IconRecord(CaptainIcon.Pacman, "ci-pacman", "e6b8"),
                new IconRecord(CaptainIcon.Ticket, "ci-ticket", "e6b9"),
                new IconRecord(CaptainIcon.MoneyBill, "ci-money-bill", "e6ba"),
                new IconRecord(CaptainIcon.BatteryEmpty, "ci-battery-empty", "e6bb"),
                new IconRecord(CaptainIcon.BatterySlash, "ci-battery-slash", "e6bc"),
                new IconRecord(CaptainIcon.BatteryQuarter, "ci-battery-quarter", "e6bd"),
                new IconRecord(CaptainIcon.BatteryHalf, "ci-battery-half", "e6be"),
                new IconRecord(CaptainIcon.BatteryFull, "ci-battery-full", "e6bf"),
                new IconRecord(CaptainIcon.BatteryBolt, "ci-battery-bolt", "e6c0"),
                new IconRecord(CaptainIcon.Book, "ci-book", "e6c2"),
                new IconRecord(CaptainIcon.Pizza, "ci-pizza", "e6c3"),
                new IconRecord(CaptainIcon.Cupcake, "ci-cupcake", "e6c4"),
                new IconRecord(CaptainIcon.Store, "ci-store", "e6c5"),
                new IconRecord(CaptainIcon.Bullseye, "ci-bullseye", "e6c6"),
                new IconRecord(CaptainIcon.BullseyeAlt, "ci-bullseye-alt", "e6c7"),
                new IconRecord(CaptainIcon.Chat, "ci-chat", "e6c9"),
                new IconRecord(CaptainIcon.Clapperboard, "ci-clapperboard", "e6ca"),
                new IconRecord(CaptainIcon.FishSkeleton, "ci-fish-skeleton", "e6cb"),
                new IconRecord(CaptainIcon.Erlenmeyer, "ci-erlenmeyer", "e6cc"),
                new IconRecord(CaptainIcon.Grape, "ci-grape", "e6cd"),
                new IconRecord(CaptainIcon.Plane, "ci-plane", "e6ce"),
                new IconRecord(CaptainIcon.PlanePaper, "ci-plane-paper", "e6df"),
                new IconRecord(CaptainIcon.Zeppelin, "ci-zeppelin", "e6cf"),
                new IconRecord(CaptainIcon.IcePop, "ci-ice-pop", "e6d0"),
                new IconRecord(CaptainIcon.IceCream, "ci-ice-cream", "e6d1"),
                new IconRecord(CaptainIcon.ThumbsUp, "ci-thumbs-up", "e6d2"),
                new IconRecord(CaptainIcon.ThumbsDown, "ci-thumbs-down", "e6d3"),
                new IconRecord(CaptainIcon.Cheese, "ci-cheese", "e6d4"),
                new IconRecord(CaptainIcon.Cake, "ci-cake", "e6d5"),
                new IconRecord(CaptainIcon.Bread, "ci-bread", "e6d6"),
                new IconRecord(CaptainIcon.Feather, "ci-feather", "e6d9"),
                new IconRecord(CaptainIcon.Globe, "ci-globe", "e6db"),
                new IconRecord(CaptainIcon.Share, "ci-share", "e6dc"),
                new IconRecord(CaptainIcon.Skype, "ci-skype", "e6dd"),
                new IconRecord(CaptainIcon.Html5, "ci-html5", "e6de"),
                new IconRecord(CaptainIcon.Tablet, "ci-tablet", "e6e0"),
                new IconRecord(CaptainIcon.Save, "ci-save", "e6e1"),
                new IconRecord(CaptainIcon.Headphones, "ci-headphones", "e6e2"),
                new IconRecord(CaptainIcon.Drawer, "ci-drawer", "e6e3"),
                new IconRecord(CaptainIcon.DrawerEmpty, "ci-drawer-empty", "e6e4"),
                new IconRecord(CaptainIcon.Terminal, "ci-terminal", "e6ed"),
                new IconRecord(CaptainIcon.Tie, "ci-tie", "e6ee"),
                new IconRecord(CaptainIcon.TieBow, "ci-tie-bow", "e6ef"),
                new IconRecord(CaptainIcon.Milkshake, "ci-milkshake", "e6f0"),
                new IconRecord(CaptainIcon.Sunglass, "ci-sunglass", "e6f1"),
                new IconRecord(CaptainIcon.QuoteLeft, "ci-quote-left", "e6f2"),
                new IconRecord(CaptainIcon.QuoteRight, "ci-quote-right", "e6f3"),
                new IconRecord(CaptainIcon.Link, "ci-link", "e6f4"),
                new IconRecord(CaptainIcon.LinkExternal, "ci-link-external", "e6f5"),
                new IconRecord(CaptainIcon.Ellipsis, "ci-ellipsis", "e6f6"),
                new IconRecord(CaptainIcon.Files, "ci-files", "e6f7"),
                new IconRecord(CaptainIcon.Arrows, "ci-arrows", "e6f8"),
                new IconRecord(CaptainIcon.ArrowsAlt, "ci-arrows-alt", "e6f9"),
                new IconRecord(CaptainIcon.ArrowsPointer, "ci-arrows-pointer", "e6fa"),
                new IconRecord(CaptainIcon.Knot, "ci-knot", "e6fb"),
                new IconRecord(CaptainIcon.DashedCircled, "ci-dashed-circled", "e6fc"),
                new IconRecord(CaptainIcon.DashedSquared, "ci-dashed-squared", "e6fd"),
                new IconRecord(CaptainIcon.Wand, "ci-wand", "e6fe"),
                new IconRecord(CaptainIcon.Scalpel, "ci-scalpel", "e6ff"),
                new IconRecord(CaptainIcon.Brush, "ci-brush", "e700"),
                new IconRecord(CaptainIcon.BrushAlt, "ci-brush-alt", "e710"),
                new IconRecord(CaptainIcon.Drop, "ci-drop", "e701"),
                new IconRecord(CaptainIcon.Magnifier, "ci-magnifier", "e702"),
                new IconRecord(CaptainIcon.Text, "ci-text", "e704"),
                new IconRecord(CaptainIcon.Stamp, "ci-stamp", "e708"),
                new IconRecord(CaptainIcon.Contrast, "ci-contrast", "e70b"),
                new IconRecord(CaptainIcon.Stars, "ci-stars", "e70c"),
                new IconRecord(CaptainIcon.Bucket, "ci-bucket", "e70d"),
                new IconRecord(CaptainIcon.ToiletPaper, "ci-toilet-paper", "e70e"),
                new IconRecord(CaptainIcon.SlidersV, "ci-sliders-v", "e70f"),
                new IconRecord(CaptainIcon.Paperclip, "ci-paperclip", "e711"),
                new IconRecord(CaptainIcon.Tools, "ci-tools", "e712"),
                new IconRecord(CaptainIcon.ArrowToLeft, "ci-arrow-to-left", "e71b"),
                new IconRecord(CaptainIcon.ArrowToLeftCircled, "ci-arrow-to-left-circled", "e725"),
                new IconRecord(CaptainIcon.ArrowToRight, "ci-arrow-to-right", "e71a"),
                new IconRecord(CaptainIcon.ArrowToRightCircled, "ci-arrow-to-right-circled", "e724"),
                new IconRecord(CaptainIcon.ArrowLeft, "ci-arrow-left", "e714"),
                new IconRecord(CaptainIcon.ArrowLeftCircled, "ci-arrow-left-circled", "e71e"),
                new IconRecord(CaptainIcon.ArrowLeftCircledDoubled, "ci-arrow-left-circled-doubled", "e723"),
                new IconRecord(CaptainIcon.ArrowLeftDoubled, "ci-arrow-left-doubled", "e719"),
                new IconRecord(CaptainIcon.ArrowRight, "ci-arrow-right", "e713"),
                new IconRecord(CaptainIcon.ArrowRightCircled, "ci-arrow-right-circled", "e71d"),
                new IconRecord(CaptainIcon.ArrowRightCircledDoubled, "ci-arrow-right-circled-doubled", "e722"),
                new IconRecord(CaptainIcon.ArrowRightDoubled, "ci-arrow-right-doubled", "e718"),
                new IconRecord(CaptainIcon.ArrowDown, "ci-arrow-down", "e715"),
                new IconRecord(CaptainIcon.ArrowDownCircled, "ci-arrow-down-circled", "e71f"),
                new IconRecord(CaptainIcon.ArrowUp, "ci-arrow-up", "e716"),
                new IconRecord(CaptainIcon.ArrowUpCircled, "ci-arrow-up-circled", "e720"),
                new IconRecord(CaptainIcon.Pause, "ci-pause", "e717"),
                new IconRecord(CaptainIcon.PauseCircle, "ci-pause-circle", "e721"),
                new IconRecord(CaptainIcon.Stop, "ci-stop", "e71c"),
                new IconRecord(CaptainIcon.StopCircle, "ci-stop-circle", "e726"),
                new IconRecord(CaptainIcon.Boy, "ci-boy", "e727"),
                new IconRecord(CaptainIcon.BoyAlt, "ci-boy-alt", "e728"),
                new IconRecord(CaptainIcon.Girl, "ci-girl", "e729"),
                new IconRecord(CaptainIcon.GirlAlt, "ci-girl-alt", "e72a"),
                new IconRecord(CaptainIcon.Picture, "ci-picture", "e72b"),
                new IconRecord(CaptainIcon.Tap, "ci-tap", "e72c"),
                new IconRecord(CaptainIcon.PlayingCard, "ci-playing-card", "e72d"),
                new IconRecord(CaptainIcon.Egg, "ci-egg", "e640"),
                new IconRecord(CaptainIcon.EggShell, "ci-egg-shell", "e72f"),
                new IconRecord(CaptainIcon.EggShellAlt, "ci-egg-shell-alt", "e730"),
                new IconRecord(CaptainIcon.ChartBar, "ci-chart-bar", "e732"),
                new IconRecord(CaptainIcon.ChartBarPie, "ci-chart-bar-pie", "e6a5"),
                new IconRecord(CaptainIcon.ChartBarIncrease, "ci-chart-bar-increase", "e731"),
                new IconRecord(CaptainIcon.ChartBarDecrease, "ci-chart-bar-decrease", "e733"),
                new IconRecord(CaptainIcon.Wifi, "ci-wifi", "e734"),
                new IconRecord(CaptainIcon.Percent, "ci-percent", "e735"),
                new IconRecord(CaptainIcon.Unlock, "ci-unlock", "e736"),
                new IconRecord(CaptainIcon.ChessHorse, "ci-chess-horse", "e737"),
                new IconRecord(CaptainIcon.Muffin, "ci-muffin", "e739"),
                new IconRecord(CaptainIcon.Denied, "ci-denied", "e73a"),
                new IconRecord(CaptainIcon.AlignJustify, "ci-align-justify", "e73b"),
                new IconRecord(CaptainIcon.AlignLeft, "ci-align-left", "e73c"),
                new IconRecord(CaptainIcon.AlignCenter, "ci-align-center", "e73d"),
                new IconRecord(CaptainIcon.AlignRight, "ci-align-right", "e73e"),
                new IconRecord(CaptainIcon.Fedora, "ci-fedora", "e740"),
                new IconRecord(CaptainIcon.SquareNut, "ci-square-nut", "e742"),
                new IconRecord(CaptainIcon.Screw, "ci-screw", "e743"),
                new IconRecord(CaptainIcon.Bottle, "ci-bottle", "e744"),
                new IconRecord(CaptainIcon.BottlePrescription, "ci-bottle-prescription", "e741"),
                new IconRecord(CaptainIcon.BottleInk, "ci-bottle-ink", "e6da"),
                new IconRecord(CaptainIcon.PowerPlug, "ci-power-plug", "e745"),
                new IconRecord(CaptainIcon.PowerOff, "ci-power-off", "e655"),
                new IconRecord(CaptainIcon.Notebook, "ci-notebook", "e746"),
                new IconRecord(CaptainIcon.NotebookAlt, "ci-notebook-alt", "e738"),
                new IconRecord(CaptainIcon.Spatula, "ci-spatula", "e747"),
                new IconRecord(CaptainIcon.Hourglass, "ci-hourglass", "e748"),
                new IconRecord(CaptainIcon.Bell, "ci-bell", "e749"),
                new IconRecord(CaptainIcon.Lifesaver, "ci-lifesaver", "e74a"),
                new IconRecord(CaptainIcon.Anchor, "ci-anchor", "e74b"),
                new IconRecord(CaptainIcon.Binoculars, "ci-binoculars", "e74c"),
                new IconRecord(CaptainIcon.PiggyBank, "ci-piggy-bank", "e74d"),
                new IconRecord(CaptainIcon.Flower, "ci-flower", "e74e"),
                new IconRecord(CaptainIcon.Flowers, "ci-flowers", "e74f"),
                new IconRecord(CaptainIcon.Weights, "ci-weights", "e750"),
                new IconRecord(CaptainIcon.Database, "ci-database", "e751"),
                new IconRecord(CaptainIcon.Ring, "ci-ring", "e752"),
                new IconRecord(CaptainIcon.Info, "ci-info", "e754"),
                new IconRecord(CaptainIcon.InfoCircle, "ci-info-circle", "e755"),
                new IconRecord(CaptainIcon.Bomb, "ci-bomb", "e756"),
                new IconRecord(CaptainIcon.University, "ci-university", "e757"),
                new IconRecord(CaptainIcon.Antenna, "ci-antenna", "e758"),
                new IconRecord(CaptainIcon.Flag, "ci-flag", "e75a"),
                new IconRecord(CaptainIcon.FlagAlt, "ci-flag-alt", "e759"),
                new IconRecord(CaptainIcon.Joystick, "ci-joystick", "e75b"),
                new IconRecord(CaptainIcon.Hand, "ci-hand", "e75c"),
                new IconRecord(CaptainIcon.Pineapple, "ci-pineapple", "e75d"),
                new IconRecord(CaptainIcon.Tangerine, "ci-tangerine", "e75e"),
                new IconRecord(CaptainIcon.Cherry, "ci-cherry", "e75f"),
                new IconRecord(CaptainIcon.Notification, "ci-notification", "e760"),
                new IconRecord(CaptainIcon.NotificationAlt, "ci-notification-alt", "e761"),
                new IconRecord(CaptainIcon.Ribbon, "ci-ribbon", "e762"),
                new IconRecord(CaptainIcon.Clock, "ci-clock", "e60c"),
                new IconRecord(CaptainIcon.ClockAlarm, "ci-clock-alarm", "e763"),
                new IconRecord(CaptainIcon.Windmill, "ci-windmill", "e765"),
                new IconRecord(CaptainIcon.Filter, "ci-filter", "e766"),
                new IconRecord(CaptainIcon.Capsule, "ci-capsule", "e767"),
                new IconRecord(CaptainIcon.Monster, "ci-monster", "e768"),
                new IconRecord(CaptainIcon.MonsterAlt, "ci-monster-alt", "e769"),
                new IconRecord(CaptainIcon.MonsterAltOne, "ci-monster-alt-one", "e76a"),
                new IconRecord(CaptainIcon.MonsterAltTwo, "ci-monster-alt-two", "e76b"),
                new IconRecord(CaptainIcon.MonsterAltThree, "ci-monster-alt-three", "e76c"),
                new IconRecord(CaptainIcon.MonsterAltFour, "ci-monster-alt-four", "e76d"),
                new IconRecord(CaptainIcon.MonsterAltFive, "ci-monster-alt-five", "e72e"),
                new IconRecord(CaptainIcon.Headset, "ci-headset", "e76e"),
                new IconRecord(CaptainIcon.RibbonsAward, "ci-ribbons-award", "e76f"),
                new IconRecord(CaptainIcon.Wheat, "ci-wheat", "e770"),
                new IconRecord(CaptainIcon.Moon, "ci-moon", "e771"),
                new IconRecord(CaptainIcon.Cloud, "ci-cloud", "e604"),
                new IconRecord(CaptainIcon.CloudSmall, "ci-cloud-small", "e772"),
                new IconRecord(CaptainIcon.CloudCog, "ci-cloud-cog", "e6ec"),
                new IconRecord(CaptainIcon.CloudCogHalved, "ci-cloud-cog-halved", "e6e6"),
                new IconRecord(CaptainIcon.CloudCheck, "ci-cloud-check", "e6e7"),
                new IconRecord(CaptainIcon.CloudRefresh, "ci-cloud-refresh", "e6e8"),
                new IconRecord(CaptainIcon.CloudSearch, "ci-cloud-search", "e6e9"),
                new IconRecord(CaptainIcon.CloudUp, "ci-cloud-up", "e6ea"),
                new IconRecord(CaptainIcon.CloudDown, "ci-cloud-down", "e6eb"),
                new IconRecord(CaptainIcon.CloudBolt, "ci-cloud-bolt", "e63b"),
                new IconRecord(CaptainIcon.CloudSunny, "ci-cloud-sunny", "e773"),
                new IconRecord(CaptainIcon.CloudWindy, "ci-cloud-windy", "e774"),
                new IconRecord(CaptainIcon.CloudRainy, "ci-cloud-rainy", "e775"),
                new IconRecord(CaptainIcon.CloudStormy, "ci-cloud-stormy", "e776")
            });

            _iconArchive.AddRange(new IIconRecord[] {
                new IconRecord(DevIcon.Git, "git", "602"),
                new IconRecord(DevIcon.GitCompare, "git_compare", "628"),
                new IconRecord(DevIcon.GitBranch, "git_branch", "625"),
                new IconRecord(DevIcon.GitCommit, "git_commit", "629"),
                new IconRecord(DevIcon.GitPullRequest, "git_pull_request", "626"),
                new IconRecord(DevIcon.GitMerge, "git_merge", "627"),
                new IconRecord(DevIcon.Bitbucket, "bitbucket", "603"),
                new IconRecord(DevIcon.GithubAlt, "github_alt", "608"),
                new IconRecord(DevIcon.GithubBadge, "github_badge", "609"),
                new IconRecord(DevIcon.Github, "github", "60a"),
                new IconRecord(DevIcon.GithubFull, "github_full", "617"),
                new IconRecord(DevIcon.Java, "java", "630"),
                new IconRecord(DevIcon.Ruby, "ruby", "639"),
                new IconRecord(DevIcon.Scala, "scala", "637"),
                new IconRecord(DevIcon.Python, "python", "63c"),
                new IconRecord(DevIcon.Go, "go", "624"),
                new IconRecord(DevIcon.RubyOnRails, "ruby_on_rails", "63b"),
                new IconRecord(DevIcon.Django, "django", "61d"),
                new IconRecord(DevIcon.Markdown, "markdown", "63e"),
                new IconRecord(DevIcon.PHP, "php", "63d"),
                new IconRecord(DevIcon.mySQL, "mysql", "604"),
                new IconRecord(DevIcon.Streamline, "streamline", "605"),
                new IconRecord(DevIcon.Database, "database", "606"),
                new IconRecord(DevIcon.Laravel, "laravel", "63f"),
                new IconRecord(DevIcon.JavaScript, "javascript", "64e"),
                new IconRecord(DevIcon.Angular, "angular", "653"),
                new IconRecord(DevIcon.Backbone, "backbone", "652"),
                new IconRecord(DevIcon.Coffeescript, "cofffeescript", "651"),
                new IconRecord(DevIcon.jQuery, "jquery", "650"),
                new IconRecord(DevIcon.Modernizr, "modernizr", "620"),
                new IconRecord(DevIcon.jQueryUI, "jquery_ui", "654"),
                new IconRecord(DevIcon.Ember, "ember", "61b"),
                new IconRecord(DevIcon.Dojo, "dojo", "61c"),
                new IconRecord(DevIcon.NodeJs, "nodejs", "619"),
                new IconRecord(DevIcon.NodeJsSmall, "nodejs_small", "618"),
                new IconRecord(DevIcon.JavaScriptShield, "javascript_shield", "64f"),
                new IconRecord(DevIcon.Bootstrap, "bootstrap", "647"),
                new IconRecord(DevIcon.SASS, "sass", "64b"),
                new IconRecord(DevIcon.CSS3full, "css3_full", "64a"),
                new IconRecord(DevIcon.CSS3, "css3", "649"),
                new IconRecord(DevIcon.HTML5, "html5", "636"),
                new IconRecord(DevIcon.HTML5Multimedia, "html5_multimedia", "632"),
                new IconRecord(DevIcon.HTML5DeviceAccess, "html5_device_access", "633"),
                new IconRecord(DevIcon.HTML53dEffects, "html5_3d_effects", "635"),
                new IconRecord(DevIcon.HTML5Connectivity, "html5_connectivity", "634"),
                new IconRecord(DevIcon.GhostSmall, "ghost_small", "614"),
                new IconRecord(DevIcon.Ghost, "ghost", "61f"),
                new IconRecord(DevIcon.Magento, "magento", "640"),
                new IconRecord(DevIcon.Joomla, "joomla", "641"),
                new IconRecord(DevIcon.JekyllSmall, "jekyll_small", "60d"),
                new IconRecord(DevIcon.Drupal, "drupal", "642"),
                new IconRecord(DevIcon.Wordpress, "wordpress", "60b"),
                new IconRecord(DevIcon.Grunt, "grunt", "64c"),
                new IconRecord(DevIcon.Bower, "bower", "64d"),
                new IconRecord(DevIcon.Npm, "npm", "61e"),
                new IconRecord(DevIcon.YahooSmall, "yahoo_small", "62d"),
                new IconRecord(DevIcon.Yahoo, "yahoo", "615"),
                new IconRecord(DevIcon.BingSmall, "bing_small", "600"),
                new IconRecord(DevIcon.Windows, "windows", "60f"),
                new IconRecord(DevIcon.Linux, "linux", "612"),
                new IconRecord(DevIcon.Ubuntu, "ubuntu", "63a"),
                new IconRecord(DevIcon.Android, "android", "60e"),
                new IconRecord(DevIcon.Apple, "apple", "611"),
                new IconRecord(DevIcon.Appstore, "appstore", "613"),
                new IconRecord(DevIcon.Phonegap, "phonegap", "630"),
                new IconRecord(DevIcon.Blackberry, "blackberry", "623"),
                new IconRecord(DevIcon.Stackoverflow, "stackoverflow", "610"),
                new IconRecord(DevIcon.Techcrunch, "techcrunch", "62c"),
                new IconRecord(DevIcon.Codrops, "coddrops", "62f"),
                new IconRecord(DevIcon.CssTricks, "css_tricks", "601"),
                new IconRecord(DevIcon.SmashingMagazine, "smashing_magazine", "62d"),
                new IconRecord(DevIcon.Netmagazine, "netmagazine", "62e"),
                new IconRecord(DevIcon.Codepen, "codepen", "616"),
                new IconRecord(DevIcon.Cssdeck, "cssdeck", "62a"),
                new IconRecord(DevIcon.Hackernews, "hackernews", "61a"),
                new IconRecord(DevIcon.Dropbox, "dropbox", "607"),
                new IconRecord(DevIcon.GoogleDrive, "google_drive", "631"),
                new IconRecord(DevIcon.VisualStudio, "visualstudio", "60c"),
                new IconRecord(DevIcon.UnitySmall, "unity_small", "621"),
                new IconRecord(DevIcon.RaspberryPi, "raspberry_pi", "622"),
                new IconRecord(DevIcon.Chrome, "chrome", "643"),
                new IconRecord(DevIcon.IE, "ie", "644"),
                new IconRecord(DevIcon.Firefox, "firefox", "645"),
                new IconRecord(DevIcon.Opera, "opera", "646"),
                new IconRecord(DevIcon.Safari, "safari", "648"),
                new IconRecord(DevIcon.Swift, "swift", "655"),
                new IconRecord(DevIcon.Symfony, "symfony", "656"),
                new IconRecord(DevIcon.SymfonyBadge, "symfony_badge", "657"),
                new IconRecord(DevIcon.Less, "less", "658"),
                new IconRecord(DevIcon.Stylus, "stylus", "659"),
                new IconRecord(DevIcon.Trello, "trello", "65a"),
                new IconRecord(DevIcon.Atlassian, "atlassian", "65b"),
                new IconRecord(DevIcon.Jira, "jira", "65c"),
                new IconRecord(DevIcon.Envato, "envato", "65d"),
                new IconRecord(DevIcon.SnapSvg, "snap_svg", "65e"),
                new IconRecord(DevIcon.Raphael, "raphael", "65f"),
                new IconRecord(DevIcon.GoogleAnalytics, "google_analytics", "660"),
                new IconRecord(DevIcon.Compass, "compass", "661"),
                new IconRecord(DevIcon.OneDrive, "onedrive", "662"),
                new IconRecord(DevIcon.Gulp, "gulp", "663"),
                new IconRecord(DevIcon.Atom, "atom", "664"),
                new IconRecord(DevIcon.Cisco, "cisco", "665"),
                new IconRecord(DevIcon.Nancy, "nancy", "666"),
                new IconRecord(DevIcon.Clojure, "clojuro", "668"),
                new IconRecord(DevIcon.ClojureAlt, "clojuro_alt", "66a"),
                new IconRecord(DevIcon.Perl, "perl", "669"),
                new IconRecord(DevIcon.Celluloid, "celluloid", "66b"),
                new IconRecord(DevIcon.W3C, "w3c", "66c"),
                new IconRecord(DevIcon.Redis, "redis", "66d"),
                new IconRecord(DevIcon.Postgresql, "postgresql", "66e"),
                new IconRecord(DevIcon.Webplatform, "webplatform", "66f"),
                new IconRecord(DevIcon.Jenkins, "jenkins", "667"),
                new IconRecord(DevIcon.RequireJS, "requirejs", "670"),
                new IconRecord(DevIcon.Opensource, "opensource", "671"),
                new IconRecord(DevIcon.Typo3, "typo3", "672"),
                new IconRecord(DevIcon.UIkit, "uikit", "673"),
                new IconRecord(DevIcon.Doctrine, "doctrine", "674"),
                new IconRecord(DevIcon.Groovy, "groovy", "675"),
                new IconRecord(DevIcon.Nginx, "nginx", "676"),
                new IconRecord(DevIcon.Haskell, "haskell", "677"),
                new IconRecord(DevIcon.Zend, "zend", "678"),
                new IconRecord(DevIcon.Gnu, "gnu", "679"),
                new IconRecord(DevIcon.Yeoman, "yeoman", "67a"),
                new IconRecord(DevIcon.Heroku, "heroku", "67b"),
                new IconRecord(DevIcon.Debian, "debian", "67d"),
                new IconRecord(DevIcon.Travis, "travis", "67e"),
                new IconRecord(DevIcon.Dotnet, "dotnet", "67f"),
                new IconRecord(DevIcon.Codeigniter, "codeigniter", "680"),
                new IconRecord(DevIcon.JavaScriptBadge, "javascript_badge", "681"),
                new IconRecord(DevIcon.Yii, "yii", "682"),
                new IconRecord(DevIcon.MsSqlServer, "mssql_server", "67c"),
                new IconRecord(DevIcon.Composer, "composer", "683"),
                new IconRecord(DevIcon.KrakenJsBadge, "krakenjs_badge", "684"),
                new IconRecord(DevIcon.KrakenJS, "krakenjs", "685"),
                new IconRecord(DevIcon.Mozilla, "mozilla", "686"),
                new IconRecord(DevIcon.Firebase, "firebase", "687"),
                new IconRecord(DevIcon.SizzleJS, "sizzlejs", "688"),
                new IconRecord(DevIcon.CreativeCommons, "creativecommons", "689"),
                new IconRecord(DevIcon.CreativeCommonsBadge, "creativecommons_badge", "68a"),
                new IconRecord(DevIcon.Mitlicence, "mitlicence", "68b"),
                new IconRecord(DevIcon.Senchatouch, "senchatouch", "68c"),
                new IconRecord(DevIcon.Bugsense, "bugsense", "68d"),
                new IconRecord(DevIcon.ExtJS, "extjs", "68e"),
                new IconRecord(DevIcon.MootoolsBadge, "mootools_badge", "68f"),
                new IconRecord(DevIcon.Mootools, "mootools", "690"),
                new IconRecord(DevIcon.RubyRough, "ruby_rough", "691"),
                new IconRecord(DevIcon.Komodo, "komodo", "692"),
                new IconRecord(DevIcon.Coda, "coda", "693"),
                new IconRecord(DevIcon.Bintray, "bintray", "694"),
                new IconRecord(DevIcon.Terminal, "terminal", "695"),
                new IconRecord(DevIcon.Code, "code", "696"),
                new IconRecord(DevIcon.Responsive, "responsive", "697"),
                new IconRecord(DevIcon.Dart, "dart", "698"),
                new IconRecord(DevIcon.Aptana, "aptana", "699"),
                new IconRecord(DevIcon.Mailchimp, "mailchimp", "69a"),
                new IconRecord(DevIcon.Netbeans, "netbeans", "69b"),
                new IconRecord(DevIcon.Dreamweaver, "dreamweaver", "69c"),
                new IconRecord(DevIcon.Brackets, "brackets", "69d"),
                new IconRecord(DevIcon.Eclipse, "eclipse", "69e"),
                new IconRecord(DevIcon.Cloud9, "cloud9", "69f"),
                new IconRecord(DevIcon.Scrum, "scrum", "6a0"),
                new IconRecord(DevIcon.Prolog, "prolog", "6a1"),
                new IconRecord(DevIcon.TerminalBadge, "terminal_badge", "6a2"),
                new IconRecord(DevIcon.CodeBadge, "code_badge", "6a3"),
                new IconRecord(DevIcon.Mongodb, "mongodb", "6a4"),
                new IconRecord(DevIcon.Meteor, "meteor", "6a5"),
                new IconRecord(DevIcon.Meteorfull, "meteorfull", "6a6"),
                new IconRecord(DevIcon.Fsharp, "fsharp", "6a7"),
                new IconRecord(DevIcon.Rust, "rust", "6a8"),
                new IconRecord(DevIcon.Ionic, "ionic", "6a9"),
                new IconRecord(DevIcon.Sublime, "sublime", "6aa"),
                new IconRecord(DevIcon.Appcelerator, "appcelerator", "6ab"),
                new IconRecord(DevIcon.Asterisk, "asterisk", "6ac"),
                new IconRecord(DevIcon.AWS, "aws", "6ad"),
                new IconRecord(DevIcon.DigitalOcean, "digital-ocean", "6ae"),
                new IconRecord(DevIcon.Dlang, "dlang", "6af"),
                new IconRecord(DevIcon.Docker, "docker", "6b0"),
                new IconRecord(DevIcon.Erlang, "erlang", "6b1"),
                new IconRecord(DevIcon.GoogleCloudPlatform, "google-cloud-platform", "6b2"),
                new IconRecord(DevIcon.Grails, "grails", "6b3"),
                new IconRecord(DevIcon.Illustrator, "illustrator", "6b4"),
                new IconRecord(DevIcon.Intellij, "intellij", "6b5"),
                new IconRecord(DevIcon.Materializecss, "materializecss", "6b6"),
                new IconRecord(DevIcon.Openshift, "openshift", "6b7"),
                new IconRecord(DevIcon.Photoshop, "photoshop", "6b8"),
                new IconRecord(DevIcon.Rackspace, "rackspace", "6b9"),
                new IconRecord(DevIcon.React, "react", "6ba"),
                new IconRecord(DevIcon.Redhat, "readhat", "6bb"),
                new IconRecord(DevIcon.Scriptcs, "scriptcs", "6bc"),
                new IconRecord(DevIcon.SQLlite, "sqllite", "6c4"),
                new IconRecord(DevIcon.VIM, "vim", "6c5")
            });
            #endregion
        }

        public IIconSizeRecord GetSize(IconSize size) => _sizeArchive.Single(rc => rc.Size == size);

        public string GetFormatTagName(IconOutputFormat format)
        {
            string result = string.Empty;

            switch (format)
            {
                case IconOutputFormat.Anchor:
                    result = "a";
                    break;

                case IconOutputFormat.Button:
                    result = "button";
                    break;

                case IconOutputFormat.Div:
                    result = "div";
                    break;

                case IconOutputFormat.Span:
                    result = "span";
                    break;

                case IconOutputFormat.Italic:
                    result = "i";
                    break;

                case IconOutputFormat.Strong:
                    result = "strong";
                    break;
            }

            return result;
        }

        public TagBuilderCustom ProcessAnchorTag(TagBuilderCustom tag, string href, TagAnchorTarget target = TagAnchorTarget.None)
        {
            if (!href.Null())
            {
                tag.AddAttribute("href", href);
            }

            if (!target.Equal(TagAnchorTarget.None))
            {
                tag.AddAttribute("target", target.ToLower());
            }

            return tag;
        }

        public IIconRecord GetIcon(Enum icon)
        {
            IIconRecord result = default;

            switch (icon)
            {
                case FontAwesomeIcon fa:
                    result = _iconArchive.Single(icn => icn.FontAwesomeIcon == (FontAwesomeIcon)icon);
                    break;

                case FriconixIcon fi:
                    result = _iconArchive.Single(icn => icn.FriconixIcon == (FriconixIcon)icon);
                    break;

                case CaptainIcon ci:
                    result = _iconArchive.Single(icn => icn.CaptainIcon == (CaptainIcon)icon);
                    break;

                case DevIcon di:
                    result = _iconArchive.Single(icn => icn.DevIcon == (DevIcon)icon);
                    break;
            }

            return result;
        }

        public string GetCaptainIconName(CaptainIcon icon)
        {
            string result = ((int)icon).ToString();

            if (result.Length == 1)
            {
                result = $"00{result}";
            }
            else if (result.Length == 2)
            {
                result = $"0{result}";
            }

            return result;
        }

        public TagBuilderCustom GetFontAwesomeTag(FontAwesomeIcon icon, IconSize size = IconSize.None)
        {
            TagBuilderCustom result = new TagBuilderCustom("i");
            result.AddCssClassRange("fa-icon", _iconArchive.Single(icn => icn.FontAwesomeIcon == icon).FontAwesomePrefix, $"fa-{_iconArchive.Single(icn => icn.FontAwesomeIcon == icon).Name}");

            if (size != IconSize.None)
            {
                result.AddCssClass(_sizeArchive.Single(sz => sz.Size == size).FontAwesomeSize);
            }

            return result;
        }
    }

    #region Enum's
    /// <summary>
    /// Supported output formats when rendering Font Awesome icon
    /// </summary>
    public enum IconOutputFormat
    {
        Span,
        Anchor,
        Button,
        Div,
        Italic,
        Strong
    }

    /// <summary>
    /// Supported icon sets
    /// </summary>
    public enum IconSet
    {
        FontAwesome,
        Friconix,
        CaptainIcon,
        DevIcon
    }

    /// <summary>
    /// Supported icon sizes
    /// </summary>
    public enum IconSize
    {
        None,
        XXS,
        XS,
        SM,
        MD,
        Normal,
        LG,
        XL,
        XXL,
        XXXL,
        X7,
        X8,
        X9
    }

    /// <summary>
    /// List of all icons in the Captain Icon set
    /// </summary>
    public enum CaptainIcon
    {
        None,
        AddressCard,
        AddressCardAlt,
        AlignCenter,
        AlignJustify,
        AlignLeft,
        AlignRight,
        Anchor,
        Antenna,
        ArrowDown,
        ArrowDownCircled,
        ArrowLeft,
        ArrowLeftCircled,
        ArrowLeftCircledDoubled,
        ArrowLeftDoubled,
        ArrowRight,
        ArrowRightCircled,
        ArrowRightCircledDoubled,
        ArrowRightDoubled,
        Arrows,
        ArrowsAlt,
        ArrowsPointer,
        ArrowToLeft,
        ArrowToLeftCircled,
        ArrowToRight,
        ArrowToRightCircled,
        ArrowUp,
        ArrowUpCircled,
        At,
        Bag,
        BallBaseball,
        BallBasket,
        BallEight,
        BallFootbal,
        Balloon,
        BalloonAlt,
        BalloonFace,
        BallSoccer,
        Banana,
        BananaPeel,
        BandAid,
        BatBaseball,
        BatteryBolt,
        BatteryEmpty,
        BatteryFull,
        BatteryHalf,
        BatteryQuarter,
        BatterySlash,
        Bell,
        Bicycle,
        Binoculars,
        Bolt,
        Bomb,
        Bone,
        Book,
        Books,
        Bottle,
        BottleInk,
        BottlePrescription,
        Bowling,
        Box,
        BoxOpened,
        Boy,
        BoyAlt,
        Bread,
        Broccoli,
        Broom,
        Brush,
        BrushAlt,
        Bucket,
        Bullseye,
        BullseyeAlt,
        ButtonClothing,
        Cake,
        Calendar,
        Camera,
        Capsule,
        Cat,
        ChartBar,
        ChartBarDecrease,
        ChartBarIncrease,
        ChartBarPie,
        Chat,
        Check,
        CheckSquared,
        Cheese,
        Cherry,
        ChessHorse,
        Chicken,
        Clapperboard,
        Clock,
        ClockAlarm,
        Cloud,
        CloudBolt,
        CloudCheck,
        CloudCog,
        CloudCogHalved,
        CloudDown,
        CloudRainy,
        CloudRefresh,
        CloudSearch,
        CloudSmall,
        CloudStormy,
        CloudSunny,
        CloudUp,
        CloudWindy,
        Coffee,
        CoffeeLong,
        Comment,
        CommentDots,
        Comments,
        Compass,
        Contrast,
        Croissant,
        Css,
        Cupcake,
        DashedCircled,
        DashedSquared,
        Database,
        Denied,
        DiscCompact,
        Domino,
        Download,
        Drawer,
        DrawerEmpty,
        Drop,
        Egg,
        EggShell,
        EggShellAlt,
        Elephant,
        Ellipsis,
        Envelope,
        EnvelopeIn,
        EnvelopeOpened,
        EnvelopeOut,
        Erlenmeyer,
        Eye,
        Facebook,
        FacebookCircled,
        FacebookSquared,
        Feather,
        Fedora,
        File,
        FileAlt,
        FileEdit,
        FileFilled,
        Files,
        Filter,
        Fire,
        FishSkeleton,
        Flag,
        FlagAlt,
        Flower,
        Flowers,
        FolderOpened,
        Foot,
        Gamepad,
        GamepadAlt,
        Gear,
        Gears,
        Ghost,
        Gift,
        Girl,
        GirlAlt,
        Git,
        Glasses,
        Globe,
        GooglePlus,
        GooglePlusCircled,
        GooglePlusSquared,
        Grape,
        Hand,
        Hanger,
        Headphones,
        Headset,
        Heart,
        Home,
        HomeAlt,
        Hourglass,
        Html5,
        IceCream,
        IcePop,
        Info,
        InfoCircle,
        Joystick,
        Key,
        KeyAlt,
        Keyboard,
        KeyboardKey,
        Knot,
        LampDesk,
        Laptop,
        Leaf,
        LeafAlt,
        LeafLeaf,
        Lemon,
        Lifesaver,
        Lightbulb,
        Link,
        Linkedin,
        LinkedinCircled,
        LinkedinSquared,
        LinkExternal,
        ListOl,
        ListUl,
        Load,
        Lock,
        LockOpened,
        Log,
        Magnifier,
        Map,
        Mashroom,
        Microwave,
        Milkshake,
        Mobile,
        MoneyBill,
        Monitor,
        Monster,
        MonsterAlt,
        MonsterAltFive,
        MonsterAltFour,
        MonsterAltOne,
        MonsterAltThree,
        MonsterAltTwo,
        Moon,
        Mouse,
        MousePointer,
        Muffin,
        Music,
        MusicNote,
        MusicPlayer,
        Mustache,
        Notebook,
        NotebookAlt,
        Notification,
        NotificationAlt,
        Octopus,
        Onion,
        Orange,
        Pacman,
        Page,
        PaintBrush,
        Paperclip,
        Pause,
        PauseCircle,
        Paw,
        Pen,
        Pencil,
        PenFountain,
        PenNib,
        Percent,
        Phone,
        Phonograph,
        Picture,
        PiggyBank,
        Pin,
        Pineapple,
        Pizza,
        Plane,
        PlanePaper,
        PlayingCard,
        PlugUsb,
        Plus,
        Portrait,
        PowerOff,
        PowerPlug,
        Print,
        PuzzlePiece,
        Question,
        QuoteLeft,
        QuoteRight,
        Refresh,
        Ribbon,
        RibbonsAward,
        Ring,
        Rocket,
        Rss,
        RssCircled,
        RssSquared,
        Ruler,
        Save,
        Scalpel,
        Screw,
        SearchMinus,
        SearchPlus,
        Share,
        Shelf,
        Ship,
        ShoppingCart,
        ShoppingCartFull,
        Sitemap,
        Skull,
        Skype,
        SlidersV,
        Spaceship,
        Spatula,
        Speaker,
        SquareNut,
        Stamp,
        Star,
        Stars,
        Stop,
        StopCircle,
        Store,
        Submarine,
        Suitcase,
        Sun,
        SunAlt,
        Sunglass,
        Tablet,
        Tachometer,
        Tag,
        TagAlt,
        Tangerine,
        Tap,
        Tape,
        Terminal,
        TestTube,
        Text,
        ThumbsDown,
        ThumbsUp,
        Thumbtack,
        ThumbtackAlt,
        Ticket,
        Tie,
        TieBow,
        Timer,
        Times,
        TimesSquared,
        ToiletPaper,
        Tools,
        Trash,
        Twitter,
        TwitterCircled,
        TwitterSquared,
        Umbrela,
        University,
        Unlock,
        Upload,
        Usb,
        User,
        UserAlt,
        Users,
        UsersAlt,
        Utensils,
        Vevo,
        VevoCircled,
        VevoSquared,
        Wand,
        Watermelon,
        Website,
        Weights,
        Whatsapp,
        WhatsappCircled,
        WhatsappSquared,
        Wheat,
        Wifi,
        Windmill,
        Youtube,
        Zeppelin,
    }

    /// <summary>
    /// Supported icons for Friconix
    /// </summary>
    public enum FriconixIcon
    {
        None,
        AmazonLogo,
        Check,
        Facebook,
        GoogleLogo,
        JavaScriptSquare,
        NetworkSolid,
        PlusSolid,
        Shopify,
        ShoppingCart,
        ShoppingCartSolid,
        ShoppingCartWide,
        TeamSolid,
        Update,
        User,
        UserCircle,
        UserCircleSolid,
        UserCircleThin,
        UserCircleWide,
        UserLock,
        UserLockSolid,
        UserLockThin,
        UserLockWide,
        UserSolid,
        UserThin,
        UserUnlock,
        UserUnlockSolid,
        UserUnlockThin,
        UserUnlockWide,
        WarningSolid
    }

    /// <summary>
    /// Supported DevIcons
    /// </summary>
    public enum DevIcon
    {
        None,
        Android,
        Angular,
        Appcelerator,
        Apple,
        Appstore,
        Aptana,
        Asterisk,
        Atlassian,
        Atom,
        AWS,
        Backbone,
        BingSmall,
        Bintray,
        Bitbucket,
        Blackberry,
        Bootstrap,
        Bower,
        Brackets,
        Bugsense,
        Celluloid,
        Chrome,
        Cisco,
        Clojure,
        ClojureAlt,
        Cloud9,
        Coda,
        Code,
        CodeBadge,
        Codeigniter,
        Codepen,
        Codrops,
        Coffeescript,
        Compass,
        Composer,
        CreativeCommons,
        CreativeCommonsBadge,
        CSS3,
        CSS3full,
        Cssdeck,
        CssTricks,
        Dart,
        Database,
        Debian,
        DigitalOcean,
        Django,
        Dlang,
        Docker,
        Doctrine,
        Dojo,
        Dotnet,
        Dreamweaver,
        Dropbox,
        Drupal,
        Eclipse,
        Ember,
        Envato,
        Erlang,
        ExtJS,
        Firebase,
        Firefox,
        Fsharp,
        Ghost,
        GhostSmall,
        Git,
        GitBranch,
        GitCommit,
        GitCompare,
        Github,
        GithubAlt,
        GithubBadge,
        GithubFull,
        GitMerge,
        GitPullRequest,
        Gnu,
        Go,
        GoogleAnalytics,
        GoogleCloudPlatform,
        GoogleDrive,
        Grails,
        Groovy,
        Grunt,
        Gulp,
        Hackernews,
        Haskell,
        Heroku,
        HTML5,
        HTML53dEffects,
        HTML5Connectivity,
        HTML5DeviceAccess,
        HTML5Multimedia,
        IE,
        Illustrator,
        Intellij,
        Ionic,
        Java,
        JavaScript,
        JavaScriptBadge,
        JavaScriptShield,
        JekyllSmall,
        Jenkins,
        Jira,
        Joomla,
        jQuery,
        jQueryUI,
        Komodo,
        KrakenJS,
        KrakenJsBadge,
        Laravel,
        Less,
        Linux,
        Magento,
        Mailchimp,
        Markdown,
        Materializecss,
        Meteor,
        Meteorfull,
        Mitlicence,
        Modernizr,
        Mongodb,
        Mootools,
        MootoolsBadge,
        Mozilla,
        MsSqlServer,
        mySQL,
        Nancy,
        Netbeans,
        Netmagazine,
        Nginx,
        NodeJs,
        NodeJsSmall,
        Npm,
        OneDrive,
        Openshift,
        Opensource,
        Opera,
        Perl,
        Phonegap,
        Photoshop,
        PHP,
        Postgresql,
        Prolog,
        Python,
        Rackspace,
        Raphael,
        RaspberryPi,
        React,
        Redhat,
        Redis,
        RequireJS,
        Responsive,
        Ruby,
        RubyOnRails,
        RubyRough,
        Rust,
        Safari,
        SASS,
        Scala,
        Scriptcs,
        Scrum,
        Senchatouch,
        SizzleJS,
        SmashingMagazine,
        SnapSvg,
        SQLlite,
        Stackoverflow,
        Streamline,
        Stylus,
        Sublime,
        Swift,
        Symfony,
        SymfonyBadge,
        Techcrunch,
        Terminal,
        TerminalBadge,
        Travis,
        Trello,
        Typo3,
        Ubuntu,
        UIkit,
        UnitySmall,
        VIM,
        VisualStudio,
        W3C,
        Webplatform,
        Windows,
        Wordpress,
        Yahoo,
        YahooSmall,
        Yeoman,
        Yii,
        Zend
    }

    /// <summary>
    /// Supported FontAwesome icons
    /// </summary>
    public enum FontAwesomeIcon
    {
        None,
        Add,
        AddCircle,
        AddCircleFull,
        AddFull,
        AddressBook,
        AddressBookFull,
        AddressCard,
        AddressCardFull,
        AmazonPay,
        AmazonPayIcon,
        AmericanExpress,
        BorderAll,
        AngleDown,
        AngleLeft,
        AngleRight,
        AngleUp,
        ApplePay,
        ApplePayIcon,
        ArrowDown,
        ArrowLeft,
        ArrowRight,
        ArrowUp,
        Bars,
        Building,
        BuildingFull,
        Bullhorn,
        Box,
        BoxOpen,
        Boxes,
        Camera,
        Calendar,
        CalendarFull,
        Check,
        CheckCircle,
        CheckCircleFull,
        CheckSquare,
        CheckSquareFull,
        Close,
        CloseCircle,
        CloseCircleFull,
        CloseFull,
        Code,
        CodeLaptop,
        Cogs,
        Comment,
        CommentFull,
        Comments,
        CommentsFull,
        Copy,
        CopyFull,
        Database,
        DeleteMinus,
        DeleteMinusCircleFull,
        DeleteMinusSquare,
        DeleteMinusSquareFull,
        DeleteTrash,
        DeleteTrashBold,
        DeleteTrashFull,
        DeleteUser,
        DeleteUserMinus,
        Diagram,
        Doc,
        DocCode,
        DocImage,
        DocPDF,
        Download,
        DownloadCloud,
        Edit,
        EditFull,
        Eye,
        EyeBold,
        Envelope,
        EnvelopeFull,
        EnvelopeOpen,
        EnvelopeOpenFull,
        FacebookLogo,
        FacebookLogoCircle,
        FacebookLogoSquare,
        FileArchive,
        FileArchiveFull,
        FileDownload,
        FileExport,
        FileUpload,
        FileAlt,
        Folder,
        FolderFull,
        FolderMinusFull,
        FolderOpen,
        FolderOpenFull,
        FolderPlusFull,
        FileImage,
        FileImageFull,
        Ghost,
        GitHub,
        Globe,
        GlobeEurope,
        GoogleDrive,
        GoogleIcon,
        GooglePlay,
        GoogleWallet,
        Handshake,
        HandshakeFull,
        Hashtag,
        Home,
        HomeDamage,
        IdBadge,
        IdBadgeFull,
        IdCard,
        IdCardFull,
        Info,
        InfoCircle,
        InstagramIcon,
        InstagramSquare,
        Image,
        ImageFull,
        Images,
        ImagesFull,
        Key,
        LaptopCode,
        Like,
        LikeFull,
        List,
        ListAlt,
        ListAltFull,
        LinkedInLogo,
        LinkedInLogoSquare,
        Lock,
        LockOpen,
        Mastercard,
        Messenger,
        Mobile,
        MobileFull,
        MoneyCheckout,
        Pager,
        PayPal,
        PayPalIcon,
        Percentage,
        Phone,
        PhoneFull,
        PhotoVideo,
        Save,
        SaveFull,
        Search,
        SearchDollar,
        SearchLocation,
        SearchMinus,
        SearchPlus,
        ShieldVirus,
        ShieldAlt,
        ShoppingBag,
        ShoppingBasket,
        ShoppingCart,
        ShoppingCartPlus,
        SignIn,
        SignOut,
        Smile,
        SmileFull,
        SmileLaugh,
        SmileLaughFull,
        SmileWink,
        SmileWinkFull,
        Stripe,
        Swatchbook,
        Tag,
        Tags,
        Tasks,
        Teeth,
        ThumbsDown,
        ThumbsDownFull,
        Thumbstick,
        ThumbsUp,
        ThumbsUpFull,
        Times,
        Truck,
        Upload,
        UploadCloud,
        User,
        UserCircle,
        UserCircleFull,
        UserFriends,
        UserFull,
        UserLock,
        UserNinja,
        UserPlusFull,
        Users,
        UserShield,
        UserSpy,
        UserTie,
        Visa,
        X,
        PaintBrush,
        PaintBrushWide,
        PaintRoller,
        Palette,
        Tools
    }

    /// <summary>
    /// Supported Friconix shapes
    /// </summary>
    public enum FriconixShape
    {
        None,
        Triangle,
        Equilateral,
        Circle,
        Square,
        Hexagon,
        Octagon
    }

    /// <summary>
    /// Supported thickness types of Friconix
    /// </summary>
    public enum FriconixThickness
    {
        None,
        Thin,
        Normal,
        Wide
    }

    /// <summary>
    /// Supported Friconix styles
    /// </summary>
    public enum FriconixStyle
    {
        None,
        Line,
        Solid,
        Prohibited
    }

    /// <summary>
    /// Supported Friconix directions
    /// </summary>
    public enum FriconixDirection
    {
        None,
        Up,
        Down,
        Left,
        Right
    }

    /// <summary>
    /// Supported effects of Friconix
    /// </summary>
    public enum FriconixEffect
    {
        None,
        Horizontal,
        Vertical,
        Spin,
        Pulse
    }
    #endregion
}
